-- Vértice Marcenaria - Supabase para frontend estático
create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  nome varchar(100) not null, telefone varchar(20), email varchar(100), cep varchar(15),
  endereco varchar(200), numero varchar(20), cpf varchar(20), criado_em timestamptz not null default now()
);
create table if not exists public.chapas_mdf (
  id bigint generated by default as identity primary key,
  nome_modelo varchar(100) not null, marca varchar(50), fornecedor varchar(100),
  preco_custo numeric(12,2) not null default 0, criado_em timestamptz not null default now()
);
create table if not exists public.ferragens (
  id bigint generated by default as identity primary key,
  tipo varchar(50) not null, nome_modelo varchar(100) not null, marca varchar(50), fornecedor varchar(100),
  preco_custo numeric(12,2) not null default 0, criado_em timestamptz not null default now()
);
create table if not exists public.config_global (
  id bigint generated by default as identity primary key,
  chave varchar(50) unique not null, valor numeric(12,4) not null
);
create table if not exists public.orcamentos (
  id bigint generated by default as identity primary key,
  projeto varchar(150) not null, cliente_id bigint references public.clientes(id) on delete set null,
  cliente_nome_avulso varchar(100), custo_producao numeric(12,2) not null default 0,
  valor_lucro numeric(12,2) not null default 0, preco_final numeric(12,2) not null default 0,
  reinvestimento_materiais numeric(12,2) not null default 0, status varchar(20) not null default 'Pendente',
  data_criacao timestamptz not null default now()
);
create table if not exists public.orcamento_itens (
  id bigint generated by default as identity primary key,
  orcamento_id bigint not null references public.orcamentos(id) on delete cascade,
  categoria varchar(30) not null, descricao varchar(200) not null,
  quantidade numeric(12,3) not null default 0, custo_unitario numeric(12,4) not null default 0,
  custo_total numeric(12,2) not null default 0
);
create index if not exists idx_orcamentos_cliente on public.orcamentos(cliente_id);
create index if not exists idx_orcamentos_data on public.orcamentos(data_criacao desc);
create index if not exists idx_orcamento_itens_orcamento on public.orcamento_itens(orcamento_id);
insert into public.config_global (chave, valor) values
('dia_trabalho',250),('luz_hora',4.5),('agua_hora',1.2),('maquina_depreciacao_hora',3),
('parafusos_un',0.15),('cola_g',0.05),('fita_borda_m',2.5),('desgaste_serra_corte',0.10),
('gasolina_km',1.80),('custo_hora_3d',50) on conflict (chave) do nothing;

-- Para uso pelo frontend com a chave pública do Supabase.
alter table public.clientes enable row level security;
alter table public.chapas_mdf enable row level security;
alter table public.ferragens enable row level security;
alter table public.config_global enable row level security;
alter table public.orcamentos enable row level security;
alter table public.orcamento_itens enable row level security;

drop policy if exists "auth clientes" on public.clientes;
drop policy if exists "auth chapas" on public.chapas_mdf;
drop policy if exists "auth ferragens" on public.ferragens;
drop policy if exists "auth config" on public.config_global;
drop policy if exists "auth orcamentos" on public.orcamentos;
drop policy if exists "auth itens" on public.orcamento_itens;
create policy "auth clientes" on public.clientes for all to authenticated using (true) with check (true);
create policy "auth chapas" on public.chapas_mdf for all to authenticated using (true) with check (true);
create policy "auth ferragens" on public.ferragens for all to authenticated using (true) with check (true);
create policy "auth config" on public.config_global for all to authenticated using (true) with check (true);
create policy "auth orcamentos" on public.orcamentos for all to authenticated using (true) with check (true);
create policy "auth itens" on public.orcamento_itens for all to authenticated using (true) with check (true);
